FROM bitnami/spark:latest

USER root

RUN apt-get update && \
    apt-get install -y python3.11 python3.11-venv python3.11-distutils && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip install --no-cache-dir numpy==1.26.3

ENV PYSPARK_PYTHON=/usr/bin/python3.11 \
    PYSPARK_DRIVER_PYTHON=/usr/bin/python3.11 \
    PYTHONPATH=/opt/airflow

USER 1001                