FROM apache/airflow:2.10.2-python3.11

USER root
# Installation de Java (requis pour spark-submit)
RUN apt-get update && \
    apt-get install -y default-jre-headless && \
    apt-get clean

USER airflow
# Installation du provider Spark pour Airflow et de pyspark compatible avec Spark 4.0 (bitnami/spark:latest)
RUN pip install --no-cache-dir "apache-airflow==2.10.2" apache-airflow-providers-apache-spark pyspark==4.0.0 pandas
